Update #5
exercemus/exercises pull request #7
Opened 2022-08-06 05:11 UTC by BoraHurst

:D

2022-08-06 15:51 UTC, GregoryConrad requested changes
Wouldn't consider an ab roller a crunch variation (or a variation on anything else for that matter). Also, could you please add a description?

2022-08-10 18:04 UTC, BoraHurst commented
I took out the variation and added a description. Is there something I missed?

2022-08-10 18:33 UTC, GregoryConrad approved these changes

2022-08-10 18:33 UTC, GregoryConrad commented
LGTM

2022-08-10 18:33 UTC, merged